<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\{Setting,Service};
class DatabaseSeeder extends Seeder { public function run(): void {
Setting::firstOrCreate(['key'=>'hero_title'],['value'=>'نحوّل فكرتك إلى تجربة رقمية تصنع أثرًا.']);
Setting::firstOrCreate(['key'=>'hero_text'],['value'=>'نطوّر مواقع وتطبيقات وحلول بيانات تساعد شركتك على العمل بشكل أفضل. من أداة بسيطة إلى منصة متكاملة، نبدأ بما تحتاجه فعلًا.']);
Setting::firstOrCreate(['key'=>'about'],['value'=>'Impact Tech شركة برمجيات تعمل على مشاريع الويب وتطبيقات الموبايل ولوحات Power BI، إلى جانب الحلول البرمجية الخفيفة والمساعدة التقنية. نفهم احتياج المشروع ونبني حلًا واضحًا يمكن تطويره مع نمو الأعمال.']);
Setting::updateOrCreate(['key'=>'email'],['value'=>'info@impacttech.digital']);
Setting::updateOrCreate(['key'=>'phone'],['value'=>'+962 7 7915 2624']);
Setting::updateOrCreate(['key'=>'whatsapp'],['value'=>'962779152624']);
Setting::firstOrCreate(['key'=>'seo_description'],['value'=>'Impact Tech — تطوير مواقع وتطبيقات موبايل ولوحات Power BI وحلول برمجية ودعم تقني للشركات والمشاريع.']);
Setting::updateOrCreate(['key'=>'brand_color'],['value'=>'#09bdb7']);
Setting::firstOrCreate(['key'=>'vision'],['value'=>'أن نكون شريكًا تقنيًا موثوقًا للشركات التي تبحث عن نمو رقمي واضح ومستدام، وأن نحول التقنية من تحدٍ إلى فرصة حقيقية للتطوير.']);
Setting::firstOrCreate(['key'=>'mission'],['value'=>'نبني حلولًا رقمية عملية تجمع بين تجربة المستخدم والبيانات والأتمتة، ونرافق عملاءنا من فهم الاحتياج حتى الإطلاق والتطوير المستمر.']);
Service::firstOrCreate(['title'=>'تطوير مواقع وتطبيقات الويب'],['description'=>'مواقع شركات، منصات أعمال وأنظمة ويب مخصصة، بتجربة سهلة ولوحة تحكم تناسب طريقة عملك.','label'=>'WEB DEVELOPMENT','sort_order'=>0,'published'=>true]);
Service::firstOrCreate(['title'=>'تطبيقات الموبايل'],['description'=>'تطبيقات للهواتف تربط عملاءك بخدماتك وتسهّل الاستخدام اليومي.','label'=>'MOBILE APPLICATIONS','sort_order'=>1,'published'=>true]);
Service::firstOrCreate(['title'=>'لوحات Power BI'],['description'=>'تحويل بيانات العمل إلى تقارير ولوحات تفاعلية تساعدك على متابعة الأداء وفهم النتائج.','label'=>'DATA & ANALYTICS','sort_order'=>2,'published'=>true]);
Service::firstOrCreate(['title'=>'حلول برمجية خفيفة'],['description'=>'أدوات بسيطة لإنجاز مهام محددة: إدارة الطلبات، النماذج، المتابعة وتنظيم البيانات.','label'=>'SMART TOOLS','sort_order'=>3,'published'=>true]);
Service::firstOrCreate(['title'=>'الدعم والمساعدة التقنية'],['description'=>'تشخيص المشاكل التقنية، المساعدة في الإعداد والمتابعة وتحسين استقرار الحلول القائمة.','label'=>'TECH SUPPORT','sort_order'=>4,'published'=>true]);
Service::firstOrCreate(['title'=>'ربط الأنظمة وأتمتة المهام'],['description'=>'ربط الخدمات عبر API وتقليل نقل البيانات يدويًا بين الأدوات.','label'=>'INTEGRATIONS','sort_order'=>5,'published'=>false]);
Service::firstOrCreate(['title'=>'صفحات هبوط ومواقع تعريفية'],['description'=>'صفحات واضحة لعرض خدمتك واستقبال استفسارات العملاء.','label'=>'LANDING PAGES','sort_order'=>6,'published'=>false]);
Service::firstOrCreate(['title'=>'صيانة وتطوير الأنظمة'],['description'=>'تحسين وظائف المواقع القائمة ومعالجة الأعطال وإضافة خصائص جديدة.','label'=>'MAINTENANCE','sort_order'=>7,'published'=>false]);
Service::firstOrCreate(['title'=>'Microsoft Dynamics 365'],['description'=>'تهيئة وتطوير حلول Dynamics 365 لتنظيم علاقات العملاء والعمليات وربط البيانات بين فرق العمل.','label'=>'MICROSOFT BUSINESS','sort_order'=>8,'published'=>true]);
Service::firstOrCreate(['title'=>'Microsoft Power Apps'],['description'=>'تطوير تطبيقات أعمال سريعة تساعد الفرق على رقمنة الإجراءات اليومية وربطها بخدمات Microsoft 365 وبيانات الشركة.','label'=>'LOW-CODE APPS','sort_order'=>9,'published'=>true]);
\App\Models\Project::firstOrCreate(['title'=>'Landing Page — تجربة رقمية 01'],['category'=>'Landing Pages','summary'=>'صفحة هبوط تعريفية تساعد شركة على عرض خدماتها وتوجيه الزائر نحو طلب الخدمة.','problem'=>'الحاجة إلى تقديم الخدمة بصورة أوضح وتسهيل وصول العميل إلى الإجراء المطلوب.','solution'=>'تصميم صفحة مركزة بهيكل محتوى واضح، عرض للخدمات، ونقاط تواصل مباشرة.','services'=>'تخطيط المحتوى، تصميم تجربة المستخدم، وتطوير الواجهة.','technologies'=>'Web Design, Responsive Development','result'=>'تجربة تعريفية منظمة وجاهزة لاستقبال استفسارات العملاء.','published'=>true,'sort_order'=>1]);
\App\Models\Project::firstOrCreate(['title'=>'Landing Page — تجربة رقمية 02'],['category'=>'Landing Pages','summary'=>'صفحة تسويقية مستقلة لإحدى الشركات، مصممة لتوضيح العرض وتحسين رحلة الاستفسار.','problem'=>'تشتت المعلومات وعدم وجود صفحة مخصصة للحملة والخدمة.','solution'=>'جمع الرسالة والعرض والخطوات المطلوبة في صفحة واحدة متجاوبة.','services'=>'استراتيجية المحتوى، UI/UX، وتطوير الويب.','technologies'=>'Laravel, Blade, Responsive UI','result'=>'صفحة تسويقية قابلة للتطوير والربط مع قنوات التواصل.','published'=>true,'sort_order'=>2]);
\App\Models\Project::firstOrCreate(['title'=>'Landing Page — تجربة رقمية 03'],['category'=>'Landing Pages','summary'=>'واجهة هبوط حديثة لإحدى الشركات تركز على الثقة وسهولة الوصول إلى الخدمة.','problem'=>'الحاجة إلى حضور رقمي أسرع وأكثر وضوحًا للخدمة المستهدفة.','solution'=>'تصميم واجهة خفيفة وسريعة مع تسلسل محتوى يخدم قرار العميل.','services'=>'تصميم واجهات، تطوير، وتجهيز المحتوى.','technologies'=>'Modern Web Stack, Mobile-first Design','result'=>'واجهة متجاوبة توصل قيمة الخدمة بطريقة مباشرة.','published'=>true,'sort_order'=>3]);
\App\Models\Project::firstOrCreate(['title'=>'تطبيق موبايل للأعمال'],['category'=>'Mobile Apps','summary'=>'تطبيق موبايل مخصص لإحدى الشركات يسهّل الوصول إلى الخدمات والعمليات من الهاتف.','problem'=>'الحاجة إلى تجربة موبايل موحدة ومناسبة للاستخدام اليومي.','solution'=>'بناء تجربة تطبيق واضحة تربط المستخدم بالخدمات والوظائف الأساسية.','services'=>'تحليل المتطلبات، UI/UX، وتطوير تطبيق الموبايل.','technologies'=>'Mobile Application, API Integration','result'=>'تجربة موبايل عملية قابلة للتوسع وإضافة الخصائص.','published'=>true,'sort_order'=>4]);
\App\Models\Project::firstOrCreate(['title'=>'لوحات Power BI تنفيذية'],['category'=>'Power BI','summary'=>'لوحات بيانات تفاعلية تساعد فرق الإدارة على متابعة مؤشرات العمل وفهم النتائج.','problem'=>'توزع البيانات وصعوبة قراءة الأداء من ملفات وتقارير متعددة.','solution'=>'تنظيم مصادر البيانات وبناء مؤشرات ولوحات تفاعلية واضحة.','services'=>'تهيئة البيانات، نمذجة البيانات، وتصميم Dashboard.','technologies'=>'Microsoft Power BI, Power Query, Data Modeling','result'=>'رؤية أوضح للبيانات ودعم أفضل للمتابعة واتخاذ القرار.','published'=>true,'sort_order'=>5]);
\App\Models\Project::firstOrCreate(['title'=>'تحليل وتنظيم البيانات الكبيرة'],['category'=>'Data Analytics','summary'=>'معالجة وتنظيم مجموعات بيانات كبيرة وتحويلها إلى معلومات قابلة للتحليل والاستخدام.','problem'=>'بيانات كبيرة ومتفرقة تحتاج إلى تنظيف وتنظيم قبل الاستفادة منها.','solution'=>'تنظيف البيانات، توحيدها، تجهيزها للتحليل، وبناء مخرجات واضحة.','services'=>'Data Cleaning, Data Transformation, Analysis','technologies'=>'SQL, Power Query, Business Intelligence','result'=>'بيانات منظمة وأسهل في التحليل وإعداد التقارير.','published'=>true,'sort_order'=>6]);
}}
