@extends('layout')
@section('body')
<main>
<section class="hero wrap"><div class="hero-copy"><span class="eyebrow">IMPACT TECH / DIGITAL SOLUTIONS</span><h1>{{ $settings['hero_title'] }}</h1><p>{{ $settings['hero_text'] }}</p><div class="actions"><a href="#contact" class="button">ابدأ مشروعك معنا ↗</a><a href="/portfolio.pdf" class="button secondary">تحميل Portfolio PDF ↓</a></div><div class="hero-tags"><span>Web</span><span>Mobile</span><span>Power Platform</span><span>Data</span></div></div><div class="hero-visual"><img src="{{ asset('images/future-loading.jpg') }}" alt="Impact Tech — Future Loading"><div class="hero-badge"><strong>Build.</strong><span>Automate.</span><span>Grow.</span></div></div></section>
<div class="capabilities" dir="ltr">WEB DEVELOPMENT <span>✳</span> MOBILE APPS <span>✳</span> MICROSOFT POWER PLATFORM <span>✳</span> DATA & BI</div>

<section id="about" class="section wrap about"><div><span class="eyebrow">01 / ABOUT IMPACT</span><h2>نفهم عملك.<br>ثم نبني له.</h2></div><div><p class="large-copy">{{ $settings['about'] }}</p><div class="vision-grid"><article><span class="eyebrow">OUR VISION</span><h3>رؤيتنا</h3><p>{{ $settings['vision'] ?? '' }}</p></article><article><span class="eyebrow">OUR MISSION</span><h3>رسالتنا</h3><p>{{ $settings['mission'] ?? '' }}</p></article></div></div></section>

<section id="services" class="section soft-section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">02 / WHAT WE DO</span><h2>خبرة تقنية تخدم<br>نمو أعمالك.</h2></div><p>من الفكرة إلى الإطلاق، نبني حلولًا قابلة للتطوير ومناسبة لطريقة عملك.</p></div><div class="service-grid">@foreach($services as $service)<article class="service-card"><div class="card-top"><span class="index">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><span class="chip">{{ $service->label }}</span></div><h3>{{ $service->title }}</h3><p>{{ $service->description }}</p></article>@endforeach</div></div></section>

<section class="microsoft-section section"><div class="wrap microsoft-grid"><div><span class="eyebrow">MICROSOFT BUSINESS SOLUTIONS</span><h2>نعمل ضمن منظومة Microsoft.</h2><p class="large-copy">نساعد الشركات على تحويل إجراءاتها اليومية إلى تطبيقات وعمليات مترابطة، مع الاستفادة من Microsoft Dynamics 365 وPower Apps وPower BI.</p></div><div class="ms-cards"><article><strong>Dynamics 365</strong><span>CRM · Operations · Customer journeys</span></article><article><strong>Power Apps</strong><span>Business apps · Workflows · Microsoft 365</span></article><article><strong>Power BI</strong><span>Dashboards · Data models · Insights</span></article></div></div></section>

<section id="team" class="section wrap"><div class="section-head"><div><span class="eyebrow">03 / OUR TEAM</span><h2>فريق يجمع التقنية<br>وفهم الأعمال.</h2></div><p>نعمل كفريق واحد لفهم التحدي وبناء حل واضح وقابل للتطوير.</p></div>@if($team->isNotEmpty())<div class="team-grid">@foreach($team as $member)<article class="team-card">@if($member->image)<img src="{{ asset('storage/'.$member->image) }}" alt="{{ $member->name }}">@else<div class="team-avatar">{{ mb_substr($member->name,0,1) }}</div>@endif<h3>{{ $member->name }}</h3><strong>{{ $member->role }}</strong><p>{{ $member->bio }}</p>@if($member->skills)<span class="chip">{{ $member->skills }}</span>@endif</article>@endforeach</div>@else<div class="team-empty"><strong>Impact Tech Team</strong><p>فريق متعدد المهارات في تطوير البرمجيات، تطبيقات الأعمال، تجربة المستخدم وتحليل البيانات.</p></div>@endif</section>

<section id="work" class="section work-section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">04 / SELECTED WORK</span><h2>حلول بنيناها<br>لتحديات حقيقية.</h2></div><p>نماذج عامة من خبراتنا، مع الحفاظ على خصوصية أسماء العملاء.</p></div>@if($projects->isNotEmpty())<div class="filters" role="group" aria-label="تصفية المشاريع"><button class="active" data-filter="all" aria-pressed="true">كل الأعمال</button>@foreach($projects->pluck('category')->unique() as $category)<button data-filter="{{ $category }}" aria-pressed="false">{{ $category }}</button>@endforeach</div><div class="project-grid">@foreach($projects as $project)<a class="project-card" data-category="{{ $project->category }}" href="/projects/{{ $project->id }}">@if($project->image)<img loading="lazy" src="{{ asset('storage/'.$project->image) }}" alt="{{ $project->title }}">@else<div class="project-placeholder"><span>{{ $project->category }}</span><strong>{{ $project->title }}</strong></div>@endif<div class="project-info"><span class="eyebrow">{{ $project->category }}</span><h3>{{ $project->title }} ↗</h3><p>{{ $project->summary }}</p></div></a>@endforeach</div>@endif</div></section>

<section class="section wrap process"><div><span class="eyebrow">05 / HOW WE WORK</span><h2>مسار واضح من الاحتياج إلى النتيجة.</h2></div><div class="steps"><div><span>01</span><h3>نفهم</h3><p>نحدد الاحتياج والأهداف والأولويات.</p></div><div><span>02</span><h3>نصمم</h3><p>نرسم تجربة وحلًا مناسبًا للعمل.</p></div><div><span>03</span><h3>نطوّر</h3><p>نبني ونختبر ونراجع التفاصيل.</p></div><div><span>04</span><h3>نطلق</h3><p>نسلّم وندعم التطوير المستمر.</p></div></div></section>

<section id="contact" class="section contact-section"><div class="wrap contact"><div><span class="eyebrow">06 / LET’S TALK</span><h2>جاهز للخطوة<br><span class="accent">الرقمية القادمة؟</span></h2><p>احكِ لنا عن مشروعك، وسنناقش معك الحل والخطوة المناسبة.</p>@if(!empty($settings['email']))<a class="contact-link" href="mailto:{{ $settings['email'] }}">{{ $settings['email'] }}</a>@endif @if(!empty($settings['phone']))<p dir="ltr">{{ $settings['phone'] }}</p>@endif @if(!empty($settings['whatsapp']))<a class="text-link" href="https://wa.me/{{ $settings['whatsapp'] }}">تواصل عبر واتساب ↗</a>@endif</div><form method="post" action="/contact" class="form-panel">@csrf<div class="two-col"><label>الاسم<input name="name" value="{{ old('name') }}" required maxlength="120" autocomplete="name"></label><label>البريد الإلكتروني<input type="email" name="email" value="{{ old('email') }}" required maxlength="254" autocomplete="email" dir="ltr"></label></div><label>الخدمة المطلوبة<select name="service" required><option value="">اختر الخدمة</option>@foreach($services as $service)<option @selected(old('service')===$service->title)>{{ $service->title }}</option>@endforeach<option @selected(old('service')==='احتياج آخر')>احتياج آخر</option></select></label><label>نبذة عن مشروعك<textarea name="message" rows="4" required minlength="10" maxlength="5000" placeholder="ما الذي تريد بناءه أو تحسينه؟">{{ old('message') }}</textarea></label><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="button" type="submit">أرسل طلبك ↗</button></form></div></section>
</main>
@endsection
