<div class="sheet slide-{{ $slide }}">
@if($slide===1)
<div class="cover">@if(!empty($settings['logo']) && file_exists(storage_path('app/public/'.$settings['logo'])))<img class="logo" src="{{ storage_path('app/public/'.$settings['logo']) }}">@else<img class="logo" src="{{ public_path('images/impact-logo.png') }}">@endif<h1>حلول رقمية تصنع أثرًا.</h1><p>نبني التجارب الرقمية التي تساعد الأعمال على التطور والنمو.</p><div class="line"></div><div class="caps" dir="ltr">WEB · MOBILE · MICROSOFT · DATA</div></div>
@elseif($slide===2)
<div class="kicker">01 / WHO WE ARE</div><table class="two"><tr><td><h1 class="title">شريك تقني<br>يفهم الأعمال.</h1></td><td><p class="lead">{{ $settings['about'] }}</p><div class="highlight">من الفكرة إلى الإطلاق والتطوير المستمر.</div></td></tr></table>
@elseif($slide===3)
<div class="kicker">02 / VISION &amp; MISSION</div><h1 class="title">نبني اليوم لما يحتاجه عملك غدًا.</h1><table class="two"><tr><td><div class="card feature"><div class="meta">OUR VISION</div><h3>رؤيتنا</h3><p>{{ $settings['vision'] ?? '' }}</p></div></td><td><div class="card feature"><div class="meta">OUR MISSION</div><h3>رسالتنا</h3><p>{{ $settings['mission'] ?? '' }}</p></div></td></tr></table>
@elseif($slide===4)
<div class="kicker">03 / OUR APPROACH</div><h1 class="title">حل واضح. تنفيذ عملي. تطوير مستمر.</h1><table class="three"><tr><td><span class="big-no">01</span><h3>نفهم الاحتياج</h3><p>نبدأ بالأهداف والتحديات وطريقة العمل الحالية.</p></td><td><span class="big-no">02</span><h3>نختار الحل المناسب</h3><p>نحدد التقنية والنطاق بما يناسب الأولويات.</p></td><td><span class="big-no">03</span><h3>نبني للنمو</h3><p>نقدم حلًا منظمًا يمكن تطويره مع توسع الأعمال.</p></td></tr></table>
@elseif($slide===5)
<div class="kicker">04 / CAPABILITIES</div><h1 class="title">خبرات مترابطة تحت سقف واحد.</h1><table class="three"><tr><td><div class="icon-box">WEB</div><h3>Web Solutions</h3><p>مواقع شركات، صفحات هبوط ومنصات أعمال.</p></td><td><div class="icon-box">APP</div><h3>Mobile Applications</h3><p>تجارب موبايل عملية وقابلة للتطوير.</p></td><td><div class="icon-box">BI</div><h3>Data &amp; Power BI</h3><p>تقارير ولوحات تساعد على فهم الأداء.</p></td></tr><tr><td><div class="icon-box">MS</div><h3>Microsoft Solutions</h3><p>Dynamics 365 وPower Apps وأتمتة العمل.</p></td><td><div class="icon-box">API</div><h3>Integrations</h3><p>ربط الأنظمة والخدمات وتدفق البيانات.</p></td><td><div class="icon-box">IT</div><h3>Technical Support</h3><p>حل المشكلات وتحسين استقرار الأنظمة.</p></td></tr></table>
@elseif($slide===6)
<div class="kicker">05 / WEB DEVELOPMENT</div><table class="two"><tr><td><h1 class="title">واجهات رقمية<br>تحوّل الزيارة إلى خطوة.</h1><p class="lead">نصمم ونطور حضورًا رقميًا واضحًا يشرح القيمة ويسهّل على العميل التواصل أو طلب الخدمة.</p></td><td><div class="stack"><b>Corporate Websites</b><span>حضور احترافي للشركات والخدمات</span><b>Landing Pages</b><span>صفحات مركزة للحملات والعروض</span><b>Custom Web Systems</b><span>أنظمة تناسب إجراءات العمل</span></div></td></tr></table>
@elseif($slide===7)
<div class="kicker">06 / MOBILE APPLICATIONS</div><table class="two"><tr><td><div class="phone-card"><span>IMPACT TECH</span><strong>Mobile-first<br>experiences.</strong><small>Simple · Useful · Scalable</small></div></td><td><h1 class="title">خدماتك أقرب<br>إلى المستخدم.</h1><p class="lead">نطوّر تطبيقات تربط المستخدم بالخدمة وتدعم العمليات اليومية، مع تجربة واضحة وربط آمن بالأنظمة الخلفية.</p></td></tr></table>
@elseif($slide===8)
<div class="kicker">07 / MICROSOFT BUSINESS SOLUTIONS</div><h1 class="title">نحو إجراءات أسرع ومعلومات أوضح.</h1><table class="three"><tr><td><div class="meta">DYNAMICS 365</div><h3>إدارة علاقات العملاء</h3><p>تنظيم رحلة العميل والعمليات والمعلومات بين الفرق.</p></td><td><div class="meta">POWER APPS</div><h3>تطبيقات أعمال سريعة</h3><p>رقمنة الإجراءات اليومية وربطها بخدمات Microsoft 365.</p></td><td><div class="meta">POWER AUTOMATE</div><h3>أتمتة سير العمل</h3><p>تقليل المهام اليدوية وتحسين تدفق الموافقات والبيانات.</p></td></tr></table>
@elseif($slide===9)
<div class="kicker">08 / POWER BI &amp; DATA</div><table class="two"><tr><td><h1 class="title">من بيانات متفرقة<br>إلى رؤية تساعد القرار.</h1><p class="lead">ننظّم البيانات ونبني نماذج وتقارير تفاعلية تمنح الإدارة صورة أوضح عن الأداء.</p></td><td><div class="dashboard"><div class="dash-row"><span></span><span></span><span></span></div><div class="dash-chart"></div><div class="dash-bars"><i></i><i></i><i></i><i></i><i></i></div></div></td></tr></table>
@elseif($slide===10)
<div class="kicker">09 / SMART TOOLS &amp; SUPPORT</div><h1 class="title">حلول خفيفة لمهام يومية مهمة.</h1><table class="three"><tr><td><h3>إدارة الطلبات</h3><p>أدوات بسيطة لتنظيم الطلبات والمتابعة.</p></td><td><h3>نماذج وإجراءات</h3><p>رقمنة جمع المعلومات والموافقات.</p></td><td><h3>دعم تقني</h3><p>تشخيص المشكلات وتحسين الاستقرار.</p></td></tr><tr><td><h3>ربط API</h3><p>تبادل البيانات بين الأنظمة والخدمات.</p></td><td><h3>تطوير قائم</h3><p>إضافة خصائص وتحسين حلول موجودة.</p></td><td><h3>استشارات تقنية</h3><p>توجيه عملي لاختيار وتنفيذ الحل المناسب.</p></td></tr></table>
@elseif($slide===11)
<div class="kicker">10 / SELECTED WORK · WEB</div><h1 class="title">صفحات هبوط لثلاث تجارب أعمال.</h1><table class="three"><tr>@foreach($projects->where('category','Landing Pages')->take(3) as $project)<td><div class="project-no">0{{ $loop->iteration }}</div><div class="meta">{{ $project->category }}</div><h3>{{ $project->title }}</h3><p>{{ $project->summary }}</p></td>@endforeach</tr></table>
@elseif($slide===12)
@php($mobile=$projects->first(fn($p)=>str_contains(strtolower($p->category),'mobile')))
<div class="kicker">11 / SELECTED WORK · MOBILE</div><table class="two"><tr><td><h1 class="title">{{ $mobile?->title ?? 'تطبيق موبايل للأعمال' }}</h1><p class="lead">{{ $mobile?->summary ?? 'تجربة موبايل مخصصة تساعد المستخدم على الوصول إلى الخدمات والعمليات الأساسية.' }}</p></td><td><div class="case-card"><div class="meta">CHALLENGE</div><p>{{ $mobile?->problem }}</p><div class="meta">SOLUTION</div><p>{{ $mobile?->solution }}</p><div class="meta">DELIVERY</div><p>{{ $mobile?->technologies }}</p></div></td></tr></table>
@elseif($slide===13)
<div class="kicker">12 / SELECTED WORK · DATA</div><h1 class="title">لوحات تنفيذية وبيانات جاهزة للتحليل.</h1><table class="two"><tr>@foreach($projects->filter(fn($p)=>in_array($p->category,['Power BI','Data Analytics']))->take(2) as $project)<td><div class="card feature"><div class="meta">{{ $project->category }}</div><h3>{{ $project->title }}</h3><p>{{ $project->summary }}</p><div class="result"><b>النتيجة</b><br>{{ $project->result }}</div></div></td>@endforeach</tr></table>
@elseif($slide===14)
<div class="kicker">13 / TEAM &amp; DELIVERY</div><h1 class="title">فريق متعدد الخبرات. مسار واحد واضح.</h1>@if($team->isNotEmpty())<table class="team-table" dir="ltr">@foreach($team->take(4)->chunk(2) as $row)<tr>@foreach($row as $member)<td><h3>{{ $member->name }}</h3><div class="role">{{ $member->role }}</div><p>{{ \Illuminate\Support\Str::limit($member->bio,150) }}</p></td>@endforeach @if($row->count()===1)<td></td>@endif</tr>@endforeach</table>@endif<table class="four"><tr><td><b>01 · Discover</b><br>فهم الاحتياج</td><td><b>02 · Design</b><br>تصميم الحل</td><td><b>03 · Build</b><br>التطوير والاختبار</td><td><b>04 · Improve</b><br>الإطلاق والتحسين</td></tr></table>
@else
<div class="closing"><div class="kicker">14 / LET'S BUILD WHAT'S NEXT</div>@if(file_exists(public_path('images/impact-logo.png')))<img class="closing-logo" src="{{ public_path('images/impact-logo.png') }}">@endif<h1>لنحوّل فكرتك<br>إلى تجربة رقمية.</h1><p>تواصل معنا لمناقشة مشروعك والخطوة المناسبة.</p><table class="contact-grid"><tr><td class="ltr">{{ $settings['email'] ?? 'info@impacttech.digital' }}</td><td class="ltr">{{ $settings['phone'] ?? '+962 7 7915 2624' }}</td><td class="ltr">impacttech.site</td></tr></table></div>
@endif
<div class="footer">IMPACT TECH · COMPANY PROFILE <span class="num">{{ str_pad($slide,2,'0',STR_PAD_LEFT) }} / 15</span></div>
</div>
