<div class="sheet">
@if($slide===1)
<div class="cover">@if(!empty($settings['logo']) && file_exists(storage_path('app/public/'.$settings['logo'])))<img class="logo" src="{{ storage_path('app/public/'.$settings['logo']) }}">@else<img class="logo" src="{{ public_path('images/impact-logo.png') }}">@endif<h1>حلول رقمية تصنع أثرًا.</h1><p>نبني التجارب الرقمية التي تساعد الأعمال على التطور والنمو.</p><div class="line"></div><div class="caps" dir="ltr">WEB DEVELOPMENT · MOBILE APPLICATIONS · MICROSOFT POWER PLATFORM · DATA &amp; BI</div></div>
@elseif($slide===2)
<div class="kicker">01 / ABOUT IMPACT TECH</div><table class="two"><tr><td><h1 class="title">نفهم عملك.<br>ثم نبني له.</h1><p class="lead">{{ $settings['about'] }}</p></td><td><div class="card" style="margin-bottom:7mm"><div class="kicker">OUR VISION</div><h3>رؤيتنا</h3><p>{{ $settings['vision'] ?? '' }}</p></div><div class="card"><div class="kicker">OUR MISSION</div><h3>رسالتنا</h3><p>{{ $settings['mission'] ?? '' }}</p></div></td></tr></table>
@elseif($slide===3)
<div class="kicker">02 / WHAT WE DO</div><h1 class="title">خبرة تقنية تخدم نمو أعمالك.</h1><table class="items">@foreach($services->take(6)->chunk(3) as $row)<tr>@foreach($row as $service)<td><div class="meta" dir="ltr">{{ $service->label }}</div><h3>{{ $service->title }}</h3><p>{{ $service->description }}</p></td>@endforeach @for($i=$row->count();$i<3;$i++)<td></td>@endfor</tr>@endforeach</table><div class="ms" dir="ltr"><table><tr><td><b>Microsoft Dynamics 365</b><span>CRM · Operations · Customer journeys</span></td><td><b>Microsoft Power Apps</b><span>Business apps · Workflows · Microsoft 365</span></td><td><b>Microsoft Power BI</b><span>Dashboards · Data models · Insights</span></td></tr></table></div>
@elseif($slide===4)
<div class="kicker">03 / OUR TEAM</div><h1 class="title">فريق يجمع التقنية وفهم الأعمال.</h1>@if($team->isNotEmpty())<table class="team-table" dir="ltr">@foreach($team->take(4)->chunk(2) as $row)<tr>@foreach($row as $member)<td><h3>{{ $member->name }}</h3><div class="role">{{ $member->role }}</div><p>{{ \Illuminate\Support\Str::limit($member->bio,210) }}</p></td>@endforeach @if($row->count()===1)<td></td>@endif</tr>@endforeach</table>@else<div class="card"><h3>Impact Tech Team</h3><p>فريق متعدد المهارات في هندسة البرمجيات وتطبيقات الموبايل وحلول Microsoft وتحليل البيانات والدعم التقني.</p></div>@endif<table class="four"><tr><td><b>01 · نفهم</b><br>الأهداف والأولويات</td><td><b>02 · نصمم</b><br>التجربة والحل</td><td><b>03 · نطوّر</b><br>البناء والاختبار</td><td><b>04 · نطلق</b><br>التسليم والدعم</td></tr></table>
@else
<div class="kicker">04 / SELECTED WORK</div><h1 class="title">حلول بنيناها لتحديات حقيقية.</h1><table class="items">@foreach($projects->take(6)->chunk(3) as $row)<tr>@foreach($row as $project)<td><div class="meta" dir="ltr">{{ $project->category }}</div><h3>{{ $project->title }}</h3><p>{{ $project->summary }}</p></td>@endforeach @for($i=$row->count();$i<3;$i++)<td></td>@endfor</tr>@endforeach</table><div class="contact"><table><tr><td><b>LET'S BUILD WHAT'S NEXT</b><br>ابدأ مشروعك معنا</td><td class="ltr">{{ $settings['email'] ?? 'info@impacttech.digital' }}</td><td class="ltr">{{ $settings['phone'] ?? '+962 7 7915 2624' }}</td><td class="ltr">impacttech.site</td></tr></table></div>
@endif
<div class="footer">IMPACT TECH · COMPANY PROFILE <span class="num">0{{ $slide }} / 05</span></div>
</div>
